K9_insys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include ('profiles.urls', namespace='profiles')),
    path('deployment/', include('deployment.urls', namespace='deployment')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('planningandacquiring/', include ('planningandacquiring.urls', namespace='planningandacquiring')),
    path('training/', include ('training.urls', namespace='training')),
    path('unitmanagement/', include ('unitmanagement.urls', namespace='unitmanagement')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deployment/urls.py
from django.urls import path
from django.conf.urls import include, url
from .import views

app_name='deployment'
urlpatterns = [
    path('', views.index, name='index'),
    path('add-area/', views.add_area, name='add_area'),
    path('add-location/', views.add_location, name='add_location'),
    path('assign-team-location/', views.assign_team_location, name='assign_team_location'),
    path('assigned-location-list/', views.assigned_location_list, name='assigned_location_list'),
    path('team-location-details/<int:id>', views.team_location_details, name='team_location_details'),
    path('edit-team/<int:id>', views.edit_team, name='edit_team'),
    path('remove-dog-deployed/<int:id>', views.remove_dog_deployed, name='remove_dog_deployed'),
    path('request_form/', views.dog_request, name='request_form'),
    path('request_dog_list/', views.request_dog_list, name='request_dog_list'),
    path('request_dog_details/<int:id>', views.request_dog_details, name='request_dog_details'),
    path('remove-dog-request/<int:id>', views.remove_dog_request, name='remove_dog_request'),
    path('view-schedule/<int:id>', views.view_schedule, name='view_schedule'),
    path('add-incident/', views.add_incident, name='add_incident'),
    path('view-incidents/', views.incident_list, name='view_incidents'),


    path('incident-detail/<int:id>', views.incident_detail, name='incident_detail'),

    path('choose-date/', views.choose_date, name='choose_date'),
    path('choose-date/deployment-report/', views.deployment_report, name='deployment_report'),

    path('deployment-area-details/', views.deployment_area_details, name='deployment_area_details'),
    path('fou-details/', views.fou_details, name='fou_details'),
    path('daily-refresher-form', views.daily_refresher_form, name='daily_refresher_form'),


    path('add-location/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('add-location/ajax_load_map', views.load_map, name='ajax_load_map'),
    path('request_form/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('request_form/ajax_load_map', views.load_map, name='ajax_load_map'),

    path('choose-location/', views.choose_location, name='choose_location'),
    path('choose-location/ajax_load_units', views.load_units, name='ajax_load_units'),
    path('choose-location/ajax_load_units_selected', views.load_units_selected, name='ajax_load_units_selected'),

    path('schedule-units', views.schedule_units, name = 'schedule_units'),

    path('pre_req_unconfirmed', views.pre_req_unconfirmed, name='pre_req_unconfirmed'),
    path('pre_req_unconfirmed/ajax_load_pre_req', views.load_pre_req, name='load_pre_req'),

    # path('dogs-deployed', views.deployed_dogs, name='deployed_dogs'),
    # path('dogs-requested', views.requested_dogs, name='requested_dogs'),
    # path('deploy-number-dogs', views.deploy_number_dogs, name='deploy_number_dogs'),
    # path('location-form', views.location_form, name='location_form'),
    # path('assign_team/', views.assign_team, name='assign_team'),
    # path('load-teams/', views.load_teams, name='ajax_load_teams'),  # <-- this one here
    # path('area_list/', views.area_list_view, name='area_list'),
    # path('add_location/', views.area_form, name='add_location'),
    # path('add_team/', views.team_form, name='add_team'),
    # path('area_detail/<int:id>', views.area_list_detail, name='area_detail'),
    #path('/<int:id>/', views., name=''),
];

inventory/urls.py
from django.urls import path
from django.conf.urls import include, url
from .import views

app_name='inventory'
urlpatterns = [
    path('', views.index, name='index'),
    #Medicine
    path('add-medicine', views.medicine_add, name='medicine_add'),
    path('edit-medicine/<int:id>/', views.medicine_edit, name='medicine_edit'),
    #Food
    path('add-food', views.food_add, name='food_add'),
    path('edit-food/<int:id>/', views.food_edit, name='food_edit'),
    #Miscellaneous
    path('add-miscellaneous', views.miscellaneous_add, name='miscellaneous_add'),
    path('edit-miscellaneous/<int:id>/', views.miscellaneous_edit, name='miscellaneous_edit'),
    #Inventory
    path('list-medicine-inventory', views.medicine_inventory_list, name='medicine_inventory_list'),
    path('list-food-inventory', views.food_inventory_list, name='food_inventory_list'),
    path('list-miscellaneous-inventory', views.miscellaneous_inventory_list, name='miscellaneous_inventory_list'),
    #inventory Details List
    path('medicine-inventory-details/<int:id>/', views.medicine_inventory_details, name='medicine_inventory_details'),
    path('food-inventory-details/<int:id>/', views.food_inventory_details, name='food_inventory_details'),
    path('miscellaneous-inventory-details/<int:id>/', views.miscellaneous_inventory_details, name='miscellaneous_inventory_details'),
    #inventory Count Form
    path('medicine-count-form/<int:id>/', views.medicine_count_form, name='medicine_count_form'),
    path('food-count-form/<int:id>/', views.food_count_form, name='food_count_form'),
    path('miscellaneous-count-form/<int:id>/', views.miscellaneous_count_form, name='miscellaneous_count_form'),
    #inventory Receive Form
    path('medicine-receive-form/<int:id>/', views.medicine_receive_form, name='medicine_receive_form'),
    path('food-receive-form/<int:id>/', views.food_receive_form, name='food_receive_form'),
    path('miscellaneous-receive-form/<int:id>/', views.miscellaneous_receive_form, name='miscellaneous_receive_form'),
    #inventory Subtract Form
    path('medicine-subtract-form/<int:id>/', views.medicine_subtract_form, name='medicine_subtract_form'),
    path('food-subtract-form/<int:id>/', views.food_subtract_form, name='food_subtract_form'),
    path('miscellaneous-subtract-form/<int:id>/', views.miscellaneous_subtract_form, name='miscellaneous_subtract_form'),
    #damaged form
    path('damaged-form', views.damaged_form, name='damaged_form'),
    path('damaged-report-list', views.damaged_report_list, name='damaged_report_list'),
];

profiles/urls.py
from django.urls import path
from django.conf.urls import include, url
from .import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from rest_framework import routers

router = routers.DefaultRouter()
router.register('user', views.UserView)


app_name='profiles'
urlpatterns = [
    path('team-leader-dashboard/', views.team_leader_dashboard, name='team_leader_dashboard'),
    path('handler-dashboard/', views.handler_dashboard, name='handler_dashboard'),
    path('vet-dashboard/', views.vet_dashboard, name='vet_dashboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('commander-dashboard/', views.commander_dashboard, name='commander_dashboard'),
    path('operations-dashboard/', views.operations_dashboard, name='operations_dashboard'),
    path('trainer-dashboard/', views.trainer_dashboard, name='trainer_dashboard'),

    path('profile/', views.profile, name='profile'),
    path('notifications/', views.notif_list, name='notif_list'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('home/', views.home, name='home'),
    path('add_User_form/', views.add_User, name='add_User_form'),
    path('add_User_form/add_personal_form/', views.add_personal_info, name='add_personal_form'),
    path('add_User_form/add_personal_form/add_education/', views.add_education, name='add_education'),
    path('add_User_form/add_personal_form/add_education/add_user_account/', views.add_user_account, name='add_user_account'),
    path('user_list/', views.user_listview, name='user_list'),
    path('user_detail/<int:id>', views.user_detailview, name='user_detail'),
    path('user_add_confirmed/', views.user_add_confirmed, name='user_add_confirmed'),
    
    path('dashboard/update_event/', views.update_event, name='update_event'),

    path('api', views.NotificationListView.as_view()),
    path('api/<int:id>', views.NotificationDetailView.as_view()),

    path('handler-dashboard/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('handler-dashboard/ajax_load_map', views.load_map, name='ajax_load_map'),
    
    path('operations-dashboard/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('operations-dashboard/ajax_load_map', views.load_map, name='ajax_load_map'),
    path('team-leader-dashboard/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('team-leader-dashboard/ajax_load_map', views.load_map, name='ajax_load_map'),

    path('operations-dashboard/ajax_load_event', views.load_event, name = "ajax_load_event"),
    path('team-leader-dashboard/ajax_load_event', views.load_event, name = "ajax_load_event"),
    path('commander-dashboard/ajax_load_event', views.load_event, name = "ajax_load_event"),
    path('dashboard/ajax_load_event', views.load_event, name = "ajax_load_event"),
    path('handler-dashboard/ajax_load_event_handler', views.load_event_handler, name = "ajax_load_event_handler"),

    path('schedule/api', views.ScheduleView.as_view()),
    path('handler-dashboard/team-location-details/<int:id>', views.team_location_details, name='team_location_details'),
    path('handler-dashboard/request_dog_details/<int:id>', views.request_dog_details, name='request_dog_details'),

    # path('user/api', views.UserListView.as_view()),
    # path('user/api/<int:id>', views.UserDetailView.as_view()),

    path('user/api', include(router.urls)),

];

training/urls.py
from django.urls import path
from django.conf.urls import include, url
from .import views

app_name='training'
urlpatterns = [
    path('', views.index, name='index'),

    path('choose-date/<int:id>', views.choose_date, name='choose_date'),

    path('choose-date/daily-record/<int:id>', views.daily_record, name='daily_record'),
    path('choose-date/daily-record/', views.daily_record_mult, name='daily_record'),

    path('record-daily/', views.record_form, name='record_daily'), #form for recording of refresher
    path('k9-record', views.k9_record, name='k9_record'), #list ng k9 with records

    path('training/list-classify-k9', views.classify_k9_list, name='classify_k9_list'),
    path('training/classify-k9/<int:id>', views.classify_k9_select, name='classify_k9_select'),
    path('training/training-record', views.training_records, name='training_records'),
    path('training/training-records', views.training_records, name='training_records'),

    path('training/update/<int:id>', views.training_update_form, name='training_update_form'),
    path('training/finalization/<int:id>', views.assign_k9_duty, name='assign_k9_duty'),
    path('training/details/<int:id>', views.training_details, name='training_details'),

    path('training/genealogy/<int:id>', views.view_family_tree, name='genealogy'),
    path('training/assign-k9/<int:id>', views.assign_k9_select, name='assign_k9_select'),
    path('training/list-k9', views.k9_training_list, name='k9_training_list'),

    path('addoption/adoption-list', views.adoption_list, name='adoption_list'),
    path('addoption/adoption-form', views.adoption_form, name='adoption_form'),
    path('addoption/adoption-form/ajax_load_form', views.load_form, name='ajax_load_form'),
    path('addoption/adoption-form/ajax_load_k9_details', views.load_k9_details, name='ajax_load_k9_details'),
    path('addoption/confirm-adoption/<int:id>', views.confirm_adoption, name='confirm_adoption'),
    path('addoption/adoption-confirmed', views.adoption_confirmed, name='adoption_confirmed'),
    path('addoption/adoption-details/<int:id>', views.adoption_details, name='adoption_details'),
    path('addoption/k9_returned/<int:id>', views.k9_returned, name='k9_returned'),

    path('fail-dog/<int:id>', views.fail_dog, name='fail_dog'),
    path('view_graph/<int:id>', views.view_graphs, name='view_graph'),

    path('training/assign-k9/ajax_load_handler', views.load_handler, name='ajax_load_handler'),
    # path('training/list-classify-k9/ajax_load_k9', views.load_k9, name='ajax_load_k9'),
    #path('/<int:id>/', views., name=''),
    path('training-finalization/<int:id>', views.serial_number_form, name='serial_number_form'),
    
    path('addoption/adoption-list/ajax_load_adoption', views.load_adoption, name='ajax_load_adoption'),
    
];

profiles/forms.py
from django import forms
from django.forms import ModelForm, ValidationError, Form, widgets
from django.contrib.admin.widgets import AdminDateWidget
from datetime import date, datetime
from .models import User, Personal_Info, Education, Account
from deployment.models import Location
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User as Auth_User

class DateInput(forms.DateInput):
    input_type = 'date'

class add_User_form(forms.ModelForm):
    class Meta:
        model = User
        fields = ('image','firstname', 'lastname', 'nickname', 'position', 'rank', 'extensionname', 'middlename',
                  'gender', 'birthdate', 'birthplace', 'civilstatus', 'citizenship', 'religion', 'bloodtype',
                  'distinct_feature', 'haircolor', 'eyecolor', 'skincolor', 'height', 'weight',
                  'headsize', 'footsize', 'bodybuild')
        widgets = {
            'birthdate': DateInput()
        }

        def __init__(self, *args, **kwargs):
            super(add_User_form, self).__init__(*args, **kwargs)
            self.fields['extensionname'].required = False
            self.fields['distinct_feature'].required = False
            self.fields['image'].required = False

class add_personal_form(forms.ModelForm):
    class Meta:
        model = Personal_Info
        fields = ('mobile_number', 'tel_number', 'street',
                  'barangay', 'city', 'province', 'mother_name', 'mother_birthdate',
                  'father_name', 'father_birthdate', 'tin', 'philhealth')
        widgets = {
            'father_birthdate': DateInput(),
            'mother_birthdate': DateInput()
        }

class add_education_form(forms.ModelForm):
    class Meta:
        model = Education
        fields = ('primary_education', 'secondary_education', 'tertiary_education', 'pe_schoolyear', 'se_schoolyear',
                  'te_schoolyear', 'pe_degree', 'se_degree', 'te_degree')

class add_user_account_form(forms.ModelForm):
   
    class Meta:
        model = Account
        fields = ('email_address', 'password')

        widgets = {
            'password': forms.PasswordInput(),
        }

        #model = Auth_User
        #fields = ('email', 'password1')

class DateForm(forms.Form):
    from_date = forms.DateField(widget=DateInput())
    to_date = forms.DateField(widget=DateInput())


class CheckArrivalForm(forms.Form):
    team_member_list = []

    team_member = forms.MultipleChoiceField(choices=team_member_list,
                                    widget=forms.CheckboxSelectMultiple())

    def __init__(self, *args, **kwargs):

        try:
            for_arrival = kwargs.pop("for_arrival", None)
        except:
            pass

        super(CheckArrivalForm, self).__init__(*args, **kwargs)
        if for_arrival:
            for_arrival_list = []
            for item in for_arrival:
                account = Account.objects.get(UserID = item.handler.id)
                for_arrival_list.append((item.handler.id , str(item.handler) + " - " + str(item.handler.rank) + " - " + str(account.serial_number)))

            print(for_arrival_list)

            self.fields['team_member'].choices = for_arrival_list

profiles/templates/profiles/global-base-ui/global_base_ui.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>K9 Coast Guard</title>
    <link rel="icon" href="{% static 'images/k9_logo.png' %}">

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'Semantic-UI/semantic.min.js' %}"></script>
    <script src="{% static 'DataTables/datatables.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'Chart.js-2.8.0/dist/Chart.bundle.min.js' %}"></script>
    <script src="js/accordion.js"></script>

    <script src="{% static 'fullcalendar-4.1.0/packages/core/main.js' %}"></script>
    <script src="{% static 'fullcalendar-4.1.0/packages/daygrid/main.js' %}"></script>
    <script src="{% static 'fullcalendar-4.1.0/packages/timegrid/main.js' %}"></script>
    <script src="{% static 'fullcalendar-4.1.0/packages/moment/main.min.js' %}"></script>


    <link rel="stylesheet" href="{% static 'Semantic-UI/semantic.min.css' %}">
    <link rel="stylesheet" href="{% static 'DataTables/datatables.css' %}">
    <link rel="stylesheet" href="{% static 'Chart.js-2.8.0/dist/Chart.min.css' %}">

    <link href="{% static 'fullcalendar-4.1.0/packages/core/main.css' %}" rel='stylesheet' />
    <link href="{% static 'fullcalendar-4.1.0/packages/daygrid/main.css' %}" rel='stylesheet' />
    <link href="{% static 'fullcalendar-4.1.0/packages/timegrid/main.css' %}" rel='stylesheet' />

    <!--Make this local-->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>

</head>
<body class="Site">
    <!--START OF TOP MENU-->
    <main class="Site-content">
        <div class="ui inverted top attached menu" style="height:50px;">
                <a class="item" style="width: 175px;" id = "menu"><i class="sidebar icon"></i>Menu</a>
                <div class="item">
                    <a class="text" href="{% url 'profiles:profile'%}">
                        <img class="ui avatar image" src="{{user.image.url}}" alt="">
                        {{request.session.session_username}}
                    </a>
                    <span></span>
                </div>
                <div class="item">
                    <strong style="color:orangered;">{{request.session.session_user_position}}</strong>
                </div>
                <div class="ui right borderless inverted menu">
                    <div class="ui item" style='border-style: none;'>
                        {% include 'profiles/global-base-ui/notification.html' %}
                    </div>
                    <div class="ui item">
                        <img  class="ui avatar image" src="{% static 'images/k9_logo.png' %}">
                        <span style="color: orangered;">PHILIPPINE K9 COAST GUARD</span>
                    </div>

                </div>
        </div>
                <!--END OF TOP MENU-->
            <!--sidebar_menu.html-->
            {% block sidebar %}
            {% endblock%}
    </main>
</body>
<style>
        .Site {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
        }

        .Site-content {
        flex: 1;
        }
    </style>



    {% block script%}
    {% endblock%}

</html>

profiles/templates/profiles/global-base-ui/notification.html
{% load static %}
<a href="{% url 'profiles:notif_list'%}">
    <div style="background-color: transparent;" class="ui icon top left pointing dropdown button" >
        <i class="blue bell icon"></i>
        <span style="color:red;font-size: 12px;">{{count}}</span>
        <div class="ui menu" style="max-height:300px;overflow:scroll;width:330px;">
                {% for notif_data in notif_data%}
                {%if notif_data.viewed == True %}

                <a class="ui feed item" style='color: black;opacity: 0.6;' href="{% url 'unitmanagement:redirect_notif' notif_data.id %}">
                      
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                {{notif_data.message|linebreaksbr }} 
                              
                            </div>
                            <div class="meta">
                                <div class="date">
                                        {{notif_data.datetime}}
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                {%else%}
                <a class="ui feed item" style='color: black;' href="{% url 'unitmanagement:redirect_notif' notif_data.id %}">
                        <div class="event">
                            <div class="content">
                                <div class="summary">
                                        {{notif_data.message}} 
                                </div>
                                <div class="meta">
                                    <div class="date">
                                            {{notif_data.datetime}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endif%}
                {% endfor%}
               
        </div>
    </div>
</a>

<style>
    .dim{
        opacity: 0.6;
        color:black;
    }
    .notdim{
        color:black;
    }

</style>

profiles/templates/profiles/global-base-ui/sidebar_menu.html
{% extends "profiles/global-base-ui/global_base_ui.html" %}

{% block sidebar%}
    <div class="ui bottom attached segment pushable">
        <div class="ui inverted labeled icon left inline vertical sidebar menu" id = "sidebar" >

            {% if request.session.session_user_position == "Administrator" %}
            <a class="item" href="{% url 'profiles:dashboard'%}"><i class="chart line icon"></i>Homepage</a>
            <a class="item" href="{% url 'profiles:profile'%}"><i class="user circle icon"></i>Profile</a>
            <a class="item" href="{% url 'planningandacquiring:K9_list'%}"><i class="clipboard list icon"></i>Planning and Acquiring</a>
            <a class="item" href="{% url 'deployment:assigned_location_list'%}"><i class="road icon"></i>Deployment</a>
            <a class="item" href="{% url 'training:training_records'%}"><i class="paw icon"></i>Training</a>
            <a class="item" href="{% url 'inventory:medicine_inventory_list'%}"><i class="warehouse icon"></i>Inventory</a>
            <a class="item" href="{% url 'profiles:user_list'%}"><i
            class="folder open icon"></i>Unit Management</a>
            <a class="item" href="{% url 'planningandacquiring:k9_performance_date'%}"><i class="folder open icon"></i>Reports</a>
            {% elif request.session.session_user_position == "Veterinarian" %}
            <a class="item" href="{% url 'profiles:vet_dashboard'%}"><i class="chart line icon"></i>Homepage</a>
            <a class="item" href="{% url 'profiles:profile'%}"><i class="user circle icon"></i>Profile</a>
            <a class="item" href="{% url 'planningandacquiring:K9_list'%}"><i class="clipboard list icon"></i>Planning and Acquiring</a>
            <a class="item" href="{% url 'inventory:medicine_inventory_list'%}"><i class="warehouse icon"></i>Inventory</a>
            <a class="item" href="{% url 'unitmanagement:k9_sick_list'%}"><i class="folder open icon"></i>Unit Management</a>
            <a class="item" href="{% url 'training:adoption_list'%}"><i class="handshake icon"></i>Adoption</a>

            {% elif request.session.session_user_position == "Team Leader" %}
             <a class="item" href="{% url 'profiles:team_leader_dashboard'%}"><i class="chart line icon"></i>Homepage</a>
            <a class="item" href="{% url 'unitmanagement:replenishment_form'%}"><i class="folder open icon"></i>Unit Management</a>
            
            {% elif request.session.session_user_position == "Handler"%}
            <a class="item" href="{% url 'profiles:handler_dashboard'%}"><i class="chart line icon"></i>Homepage</a>
            <a class="item" href="{% url 'profiles:profile'%}"><i class="user circle icon"></i>Profile</a>
            <a class="item" href="{% url 'unitmanagement:health_history_handler'%}"><i class="folder open icon"></i>Unit Management</a>
            
            {% elif request.session.session_user_position == "Trainer"%}
            <a class="item" href="{% url 'profiles:trainer_dashboard'%}"><i class="chart line icon"></i>Homepage</a>
            <a class="item" href="{% url 'profiles:profile'%}"><i class="user circle icon"></i>Profile</a>
            <a class="item" href="{% url 'training:classify_k9_list'%}"><i class="paw icon"></i>Training</a>
            <!--<a class="item" href="{% url 'unitmanagement:health_history_handler'%}"><i class="folder open icon"></i>Unit Management</a>-->

            {% elif request.session.session_user_position == "Commander"%}
            <a class="item" href="{% url 'profiles:commander_dashboard'%}"><i class="chart line icon"></i>Homepage</a>
            <a class="item" href="{% url 'deployment:assigned_location_list'%}"><i class="road icon"></i>Deployment</a>

            {% elif request.session.session_user_position == "Operations"%}
            <a class="item" href="{% url 'profiles:operations_dashboard'%}"><i class="chart line icon"></i>Homepage</a>

            {% else %}
            <a class="item" href="{% url 'profiles:team_leader_dashboard'%}"><i class="chart line icon"></i>Homepage</a>
            <a class="item" href="{% url 'profiles:profile'%}"><i class="user circle icon"></i>Profile</a>
            <a class="item" href="{% url 'deployment:deployment_area_details'%}"><i class="folder open icon"></i>Unit Management</a>
                        
            {% endif %}

            <a class="item" href="{% url 'profiles:logout'%}">Logout</a>
        </div>
        
        <!--html pages-->
       
        <div class="pusher">
                {% block sidebar_module %}
                {% endblock%}
                {% block dashboard %}
                {% endblock%}

        </div>
        
    </div>
{% endblock%}


{% block script%}
<script>
    $(document).ready(function(){
        $( "#menu" ).on("click", function() {
            $('#sidebar').sidebar({
                context: $('.bottom.segment')
            }).sidebar('attach events', '.menu .item');
        });


        $('.ui.menu .ui.dropdown').dropdown({
            on: 'hover'
        });

        $('.ui.menu .item').on('click', function() {
            $(this)
            .addClass('active')
            .siblings()
            .removeClass('active');
        })
    });
</script>

{% endblock%}