K9_insys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include ('profiles.urls', namespace='profiles')),
    path('deployment/', include('deployment.urls', namespace='deployment')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('planningandacquiring/', include ('planningandacquiring.urls', namespace='planningandacquiring')),
    path('training/', include ('training.urls', namespace='training')),
    path('unitmanagement/', include ('unitmanagement.urls', namespace='unitmanagement')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deployment/urls.py
from django.urls import path
from django.conf.urls import include, url
from .import views

app_name='deployment'
urlpatterns = [
    path('', views.index, name='index'),
    path('add-area/', views.add_area, name='add_area'),
    path('add-location/', views.add_location, name='add_location'),
    path('assign-team-location/', views.assign_team_location, name='assign_team_location'),
    path('assigned-location-list/', views.assigned_location_list, name='assigned_location_list'),
    path('team-location-details/<int:id>', views.team_location_details, name='team_location_details'),
    path('edit-team/<int:id>', views.edit_team, name='edit_team'),
    path('remove-dog-deployed/<int:id>', views.remove_dog_deployed, name='remove_dog_deployed'),
    path('request_form/', views.dog_request, name='request_form'),
    path('request_dog_list/', views.request_dog_list, name='request_dog_list'),
    path('request_dog_details/<int:id>', views.request_dog_details, name='request_dog_details'),
    path('remove-dog-request/<int:id>', views.remove_dog_request, name='remove_dog_request'),
    path('view-schedule/<int:id>', views.view_schedule, name='view_schedule'),
    path('add-incident/', views.add_incident, name='add_incident'),
    path('view-incidents/', views.incident_list, name='view_incidents'),


    path('incident-detail/<int:id>', views.incident_detail, name='incident_detail'),

    path('choose-date/', views.choose_date, name='choose_date'),
    path('choose-date/deployment-report/', views.deployment_report, name='deployment_report'),

    path('deployment-area-details/', views.deployment_area_details, name='deployment_area_details'),
    path('fou-details/', views.fou_details, name='fou_details'),
    path('daily-refresher-form', views.daily_refresher_form, name='daily_refresher_form'),


    path('add-location/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('add-location/ajax_load_map', views.load_map, name='ajax_load_map'),
    path('request_form/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('request_form/ajax_load_map', views.load_map, name='ajax_load_map'),

    path('choose-location/', views.choose_location, name='choose_location'),
    path('choose-location/ajax_load_units', views.load_units, name='ajax_load_units'),
    path('choose-location/ajax_load_units_selected', views.load_units_selected, name='ajax_load_units_selected'),

    path('schedule-units', views.schedule_units, name = 'schedule_units'),

    path('pre_req_unconfirmed', views.pre_req_unconfirmed, name='pre_req_unconfirmed'),
    path('pre_req_unconfirmed/ajax_load_pre_req', views.load_pre_req, name='load_pre_req'),

    # path('dogs-deployed', views.deployed_dogs, name='deployed_dogs'),
    # path('dogs-requested', views.requested_dogs, name='requested_dogs'),
    # path('deploy-number-dogs', views.deploy_number_dogs, name='deploy_number_dogs'),
    # path('location-form', views.location_form, name='location_form'),
    # path('assign_team/', views.assign_team, name='assign_team'),
    # path('load-teams/', views.load_teams, name='ajax_load_teams'),  # <-- this one here
    # path('area_list/', views.area_list_view, name='area_list'),
    # path('add_location/', views.area_form, name='add_location'),
    # path('add_team/', views.team_form, name='add_team'),
    # path('area_detail/<int:id>', views.area_list_detail, name='area_detail'),
    #path('/<int:id>/', views., name=''),
];

deployment/models.py
from django.db import models
# from planningandacquiring.models import K9
# from inventory.models import Food, Medicine_Inventory
from profiles.models import User
from datetime import timedelta, date, datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
import re
from django.utils import timezone

# Create your models here.
class Area(models.Model):
    name = models.CharField('name', max_length=150, default='')
    commander = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

class Location(models.Model):

    TYPE = (
        ('Mall', 'Mall'),
        ('Airport', 'Airport'),
        ('Government Building', 'Government Building')
    )

    CITY = (
        ('Alaminos', 'Alaminos'),
        ('Angeles', 'Angeles'),
        ('Antipolo', 'Antipolo'),
        ('Bacolod', 'Bacolod'),
        ('Bacoor', 'Bacoor'),
        ('Bago', 'Bago'),
        ('Baguio', 'Baguio'),
        ('Bais', 'Bais'),
        ('Balanga', 'Balanga'),
        ('Batac', 'Batac'),
        ('Batangas', 'Batangas'),
        ('Bayawan', 'Bayawan'),
        ('Baybay', 'Baybay'),
        ('Bayugan', 'Bayugan'),
        ('Biñan', 'Biñan'),
        ('Bislig', 'Bislig'),
        ('Bogo', 'Bogo'),
        ('Borongan', 'Borongan'),
        ('Butuan', 'Butuan'),
        ('Cabadbaran', 'Cabadbaran'),
        ('Cabanatuan', 'Cabanatuan'),
        ('Cabuyao', 'Cabuyao'),
        ('Cadiz', 'Cadiz'),
        ('Cagayan de Oro', 'Cagayan de Oro'),
        ('Calamba', 'Calamba'),
        ('Calapan', 'Calapan'),
        ('Calbayog', 'Calbayog'),
        ('Caloocan', 'Caloocan'),
        ('Candon', 'Candon'),
        ('Canlaon', 'Canlaon'),
        ('Carcar', 'Carcar'),
        ('Catbalogan', 'Catbalogan'),
        ('Cauayan', 'Cauayan'),
        ('Cavite', 'Cavite'),
        ('Cebu', 'Cebu'),
        ('Cotabato', 'Cotabato'),
        ('Dagupan', 'Dagupan'),
        ('Danao', 'Danao'),
        ('Dapitan', 'Dapitan'),
        ('Dasmariñas', 'Dasmariñas'),
        ('Davao', 'Davao'),
        ('Digos', 'Digos'),
        ('Dipolog', 'Dipolog'),
        ('Dumaguete', 'Dumaguete'),
        ('El Salvador', 'El Salvador'),
        ('Escalante', 'Escalante'),
        ('Gapan', 'Gapan'),
        ('General Santos', 'General Santos'),
        ('General Trias', 'General Trias'),
        ('Gingoog', 'Gingoog'),
        ('Guihulngan', 'Guihulngan'),
        ('Himamaylan', 'Himamaylan'),
        ('Ilagan', 'Ilagan'),
        ('Iligan', 'Iligan'),
        ('Iloilo', 'Iloilo'),
        ('Imus', 'Imus'),
        ('Iriga', 'Iriga'),
        ('Isabela', 'Isabela'),
        ('Kabankalan', 'Kabankalan'),
        ('Kidapawan', 'Kidapawan'),
        ('Koronadal', 'Koronadal'),
        ('La Carlota', 'La Carlota'),
        ('Lamitan', 'Lamitan'),
        ('Laoag', 'Laoag'),
        ('Lapu‑Lapu', 'Lapu‑Lapu'),
        ('Las Piñas', 'Las Piñas'),
        ('Legazpi', 'Legazpi'),
        ('Ligao', 'Ligao'),
        ('Lipa', 'Lipa'),
        ('Lucena', 'Lucena'),
        ('Maasin', 'Maasin'),
        ('Mabalacat', 'Mabalacat'),
        ('Makati', 'Makati'),
        ('Malabon', 'Malabon'),
        ('Malaybalay', 'Malaybalay'),
        ('Malolos', 'Malolos'),
        ('Mandaluyong', 'Mandaluyong'),
        ('Mandaue', 'Mandaue'),
        ('Manila', 'Manila'),
        ('Marawi', 'Marawi'),
        ('Marikina', 'Marikina'),
        ('Masbate', 'Masbate'),
        ('Mati', 'Mati'),
        ('Meycauayan', 'Meycauayan'),
        ('Muñoz', 'Muñoz'),
        ('Muntinlupa', 'Muntinlupa'),
        ('Naga - Camarines Sur', 'Naga - Camarines Sur'),
        ('Naga - Cebu', 'Naga - Cebu'),
        ('Navotas', 'Navotas'),
        ('Olongapo', 'Olongapo'),
        ('Ormoc', 'Ormoc'),
        ('Oroquieta', 'Oroquieta'),
        ('Ozamiz', 'Ozamiz'),
        ('Pagadian', 'Pagadian'),
        ('Palayan', 'Palayan'),
        ('Panabo', 'Panabo'),
        ('Parañaque', 'Parañaque'),
        ('Pasay', 'Pasay'),
        ('Pasig', 'Pasig'),
        ('Passi', 'Passi'),
        ('Puerto Princesa', 'Puerto Princesa'),
        ('Quezon', 'Quezon'),
        ('Roxas', 'Roxas'),
        ('Sagay', 'Sagay'),
        ('Samal', 'Samal'),
        ('San Carlos - Negros Occidental', 'San Carlos - Negros Occidental'),
        ('San Carlos - Pangasinan', 'San Carlos - Pangasinan'),
        ('San Fernando - La Union', 'San Fernando - La Union'),
        ('San Fernando - Pampanga', 'San Fernando - Pampanga'),
        ('San Jose', 'San Jose'),
        ('San Jose del Monte', 'San Jose del Monte'),
        ('San Juan', 'San Juan'),
        ('San Pablo', 'San Pablo'),
        ('San Pedro', 'San Pedro'),
        ('Santa Rosa', 'Santa Rosa'),
        ('Santiago', 'Santiago'),
        ('Silay', 'Silay'),
        ('Sipalay', 'Sipalay'),
        ('Sorsogon', 'Sorsogon'),
        ('Surigao', 'Surigao'),
        ('Tabaco', 'Tabaco'),
        ('Tabuk', 'Tabuk'),
        ('Tacloban', 'Tacloban'),
        ('Tacurong', 'Tacurong'),
        ('Tagaytay', 'Tagaytay'),
        ('Tagbilaran', 'Tagbilaran'),
        ('Taguig', 'Taguig'),
        ('Tagum', 'Tagum'),
        ('Talisay - Cebu', 'Talisay - Cebu'),
        ('Talisay - Negros Occidental', 'Talisay - Negros Occidental'),
        ('Tanauan', 'Tanauan'),
        ('Tandag', 'Tandag'),
        ('Tangub', 'Tangub'),
        ('Tanjay', 'Tanjay'),
        ('Tarlac', 'Tarlac'),
        ('Tayabas', 'Tayabas'),
        ('Toledo', 'Toledo'),
        ('Trece Martires', 'Trece Martires'),
        ('Tuguegarao', 'Tuguegarao'),
        ('Urdaneta', 'Urdaneta'),
        ('Valencia', 'Valencia'),
        ('Valenzuela', 'Valenzuela'),
        ('Victorias', 'Victorias'),
        ('Vigan', 'Vigan'),
        ('Zamboanga', 'Zamboanga'),
    )
    area = models.ForeignKey(Area, on_delete=models.CASCADE, null=True, blank=True)
    place = models.CharField('place', max_length=500, default='Undefined')
    city = models.CharField('city', choices=CITY, max_length=100, default='None')
    #sector_type = models.CharField('sector_type', choices=TYPE, max_length=100, null=True, blank=True)
    status = models.CharField('status', max_length=100, default="unassigned")
    longtitude = models.DecimalField('longtitude', max_digits=50, decimal_places=4, null=True)
    latitude = models.DecimalField('latitude', max_digits=50, decimal_places=4, null=True)

    def __str__(self):
        return str(self.area) + ' : ' + ' - ' + str(self.place)

class Team_Assignment(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE, null=True, blank=True)
    team_leader =  models.ForeignKey(User, on_delete=models.CASCADE,  null=True, blank=True)
    team = models.CharField('team', max_length=100)
    EDD_demand = models.IntegerField('EDD_demand', default=2)
    NDD_demand = models.IntegerField('NDD_demand', default=2)
    SAR_demand = models.IntegerField('SAR_demand', default=1)
    EDD_deployed = models.IntegerField('EDD_deployed', default=0)
    NDD_deployed = models.IntegerField('NDD_deployed', default=0)
    SAR_deployed = models.IntegerField('SAR_deployed', default=0)
    total_dogs_demand = models.IntegerField('total_dogs_demand', default=0)
    total_dogs_deployed = models.IntegerField('total_dogs_deployed', default=0)
    date_added = models.DateField('date_added', auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.team)

    def generate_team_name(self):
        team_name = ""

        location = self.location
        x_list = re.split("\s", str(location.area))
        new_x = ""
        for x in x_list:
            print(x[0])
            new_x += x[0]

        team_name += new_x
        team_name += "-"
        team_name += location.city
        team_name += "-"

        words = location.place.split(",")
        team_name += words[0]

        return team_name


    def save(self, *args, **kwargs):
        self.total_dogs_demand = int(self.EDD_demand) + int(self.NDD_demand) + int(self.SAR_demand)
        self.total_dogs_deployed = int(self.EDD_deployed) + int(self.NDD_deployed) + int(self.SAR_deployed)

        if self.location:
            self.team = self.generate_team_name()

        super(Team_Assignment, self).save(*args, **kwargs)

class Dog_Request(models.Model):
    TYPE = (
        # ('Disaster', 'Disaster'),
        # ('Annual Event', 'Annual Event'),
        ('Big Event', 'Big Event'),
        ('Small Event', 'Small Event'),
    )

    CITY = (
        ('Alaminos', 'Alaminos'),
        ('Angeles', 'Angeles'),
        ('Antipolo', 'Antipolo'),
        ('Bacolod', 'Bacolod'),
        ('Bacoor', 'Bacoor'),
        ('Bago', 'Bago'),
        ('Baguio', 'Baguio'),
        ('Bais', 'Bais'),
        ('Balanga', 'Balanga'),
        ('Batac', 'Batac'),
        ('Batangas', 'Batangas'),
        ('Bayawan', 'Bayawan'),
        ('Baybay', 'Baybay'),
        ('Bayugan', 'Bayugan'),
        ('Biñan', 'Biñan'),
        ('Bislig', 'Bislig'),
        ('Bogo', 'Bogo'),
        ('Borongan', 'Borongan'),
        ('Butuan', 'Butuan'),
        ('Cabadbaran', 'Cabadbaran'),
        ('Cabanatuan', 'Cabanatuan'),
        ('Cabuyao', 'Cabuyao'),
        ('Cadiz', 'Cadiz'),
        ('Cagayan de Oro', 'Cagayan de Oro'),
        ('Calamba', 'Calamba'),
        ('Calapan', 'Calapan'),
        ('Calbayog', 'Calbayog'),
        ('Caloocan', 'Caloocan'),
        ('Candon', 'Candon'),
        ('Canlaon', 'Canlaon'),
        ('Carcar', 'Carcar'),
        ('Catbalogan', 'Catbalogan'),
        ('Cauayan', 'Cauayan'),
        ('Cavite', 'Cavite'),
        ('Cebu', 'Cebu'),
        ('Cotabato', 'Cotabato'),
        ('Dagupan', 'Dagupan'),
        ('Danao', 'Danao'),
        ('Dapitan', 'Dapitan'),
        ('Dasmariñas', 'Dasmariñas'),
        ('Davao', 'Davao'),
        ('Digos', 'Digos'),
        ('Dipolog', 'Dipolog'),
        ('Dumaguete', 'Dumaguete'),
        ('El Salvador', 'El Salvador'),
        ('Escalante', 'Escalante'),
        ('Gapan', 'Gapan'),

deployment/templates/deployment/ajax_load_teams.html
<option value="">---------</option>
{% for team in teams %}
<option value="{{ team.pk }}">{{ team.name }}</option>
{% endfor %}

deployment/templates/deployment/assign_team.html
{% extends "profiles/sidebar_deployment.html" %}

{% block content %}
<h2 class="ui header">
    {{title}}
    <div class="sub header">Input location details Here</div>
</h2>
       
<div class="ui fluid container">
    <div class="ui inverted segment">
        {% if messages %}
            {% for message in messages %}
                <div class="{{ style }}">{{message}}</div>
            {% endfor %}
        {% endif %}
    <form class="ui inverted equal width form" id="area_team_form" action="{% url 'deployment:assign_team' %}" data-teams-url="{% url 'deployment:ajax_load_teams' %}" method="POST" novalidate>
        {% csrf_token %}
        <div class="fields">
            <div class="field">
                <label>Area</label>
                {{form.area}}
            </div>
            <div class="field">
                <label>Team</label>
                {{form.team}}
            </div>
        </div>

       <div class="fields">
            <div class="field">
                <label>Number of Handlers needed</label>
                {{form.handlers}}
            </div>
            <div class="field">
                <label>Number of Explosives needed</label>
                {{form.EDD}}
            </div>
       </div>

        <div class="fields">
            <div class="field">
                <label>Number of Narcotics needed</label>
                {{form.NDD}}
            </div>
            <div class="field">
                <label>Number of Search and Rescue needed</label>
                {{form.SAR}}
            </div>
        </div>

        <div class="ui inverted right aligned segment" style="padding: 0px;" style="border-width: 0px;">
            <button class = "ui button green" type="submit" onclick="return confirm('Are you sure?')">Submit</button>
        </div>
    </form>
    </div>
</div>

  <script>
    $("#id_area").change(function () {
      var url = $("#area_team_form").attr("data-teams-url");  // get the url of the `load_teams` view
      var areaId = $(this).val();  // get the selected area ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'area': areaId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_teams` view function
          $("#id_team").html(data);  // replace the contents of the teams input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

deployment/templates/deployment/assigned_location_list.html
{% extends "profiles/sidebar_deployment.html" %}
{% load index %}
{% block content %}
<div class="ui inverted segment" style="padding:20px;">
		<h3 class="ui header">{{ title }}</h3>
		{% if messages %}
			{% for message in messages %}
				<div class="{{style}}" > {{ message }}</div>
			{% endfor %}
		{% endif %}
	</div>
		<table id="tabledata" class="ui seven column celled table">
        	<thead>
          	<tr>
              <th>Team</th>
							<th>Area</th>
							<th>City</th>
							<th>Place</th>
							<th>No. of Maritime</th>
							<th>No. of Incidents</th>
							<th>No. of Units Deployed</th>
							<th></th>
          	</tr>
    		</thead>
    		<tbody>
				{% for data in data %}
    				<tr>
							<td>
								<a href="{% url 'deployment:team_location_details' data.id %}">{{data.team }}</a>
							</td>
							<td>{{data.location.area}}</td>
							<td>{{data.location.city}}</td>
							<td>{{data.location.place}}</td>
							<td>{{data.location|maritime_count_location:0 }}</td>
							<td>{{data.location|incident_count_location:0 }}</td>
							<td>{{data.total_dogs_deployed}} out of 5</td>
							<td class="ui center aligned">
								<a href="{% url 'deployment:edit_team' data.id %}" class="ui basic blue button">Edit</a>
							</td>
    				</tr>
				{% endfor %}
        </tbody>
    </table>

<script type="text/javascript">


	$('#tabledata').DataTable( {
        "order": [[ 0, "asc" ]]
    });
	$('.menu .item').tab();
	
</script>
{% endblock %}

deployment/templates/deployment/incident_detail.html
{% extends "profiles/sidebar_deployment.html" %}
{% load index %}

{% block content %}
<div class = "ui inverted segment">
<h1>{{title}}</h1>
</div>

<div class = "ui segment">

		<table class="ui two column celled table">
            <thead>
        	<tr>
            <th>Reported by</th>
                <td>{{incident.user}}</td>
            </tr>
            <th>Date</th>
                <td>{{incident.date}}</td>
            </tr>
            <th>Location</th>
                <td>{{incident.location}}</td>
            </tr>
            <th>Type</th>
                <td>{{incident.type}}</td>
            </tr>
            <th>Report</th>
            <td><textarea rows="4" cols="50">{{incident.remarks}}</textarea></td>
            </tr>
            </thead>
    </table>
</div>

{% endblock %}

deployment/templates/deployment/incident_list.html
{% extends "profiles/sidebar_deployment.html" %}
{% load index %}

{% block content %}
<div class="ui inverted segment" style="padding:20px;">
    <h1 class="ui header">{{ title }}</h1>

</div>

<div class = "ui segment">

		<table id="tabledata" class="ui celled table">
        	<thead>
          	<tr>
            <th>Date</th>
                <th>Location</th>
                <th>Type</th>
				<th></th>
          	</tr>
    		</thead>
    		<tbody>
				{% for incident in incidents %}
    				<tr>
                        <td>{{ incident.date |date:'Y-m-d'}}</td>
                        <td>{{ incident.location }}</td>
                        <td>{{ incident.type }}</td>
						<td><a href="{% url 'deployment:incident_detail' incident.id %}">View Details</a></td>
    				</tr>
				{% endfor %}
        </tbody>
    </table>
</div>

<script type="text/javascript">

	$('#tabledata').DataTable( {
        "order": [[ 0, "desc" ],[ 1, "asc" ]]
    });
	$('.menu .item').tab();


</script>
{% endblock %}

deployment/templates/deployment/request_form.html
{% extends "profiles/sidebar_deployment.html" %}

{% load um_tags %}
{% load widget_tweaks %}

{% block content %}
<h2 class="ui header">
    {{title}}
    {{geoform.media}}
    <div class="sub header">Input request details here</div>
</h2>
       
<div class="ui fluid container">
    <form class="ui equal width form" id="request_form" action="{% url 'deployment:request_form' %}" method="POST">
    <div class="ui inverted segment">
        {% if messages %}
            {% for message in messages %}
                <div class="{{ style }}">{{message}}</div>
            {% endfor %}
        {% endif %}

        {% csrf_token %}
        <div class="fields">
            <div class="field">
                <label>Requester</label>
                {{form.requester}}
            </div>

            <div class="field">
                <label>Event Name</label>
                {{form.event_name}}
            </div>

        </div>

        <div class="fields">

            <div class="field">
                <label>Area</label>
                {{form.area}}
            </div>
            <div class="field">
                <label>Phone Number</label>
                {{form.phone_number}}
            </div>
            <div class="field">
                <label>Email Address</label>
                {{form.email_address}}
            </div>

            <div class="field">
                <label>Number of K9s needed</label>
                {{form.k9s_needed}}
            </div>

        </div>



         <div class="fields">
            <div class="field">
                <label>Start of Event</label>
                {{form.start_date}}
            </div>
            <div class="field">
                <label>End of Event</label>
                {{form.end_date}}
            </div>
        </div>
        <div class="fields">
            <div class="six wide field">
                <label>Area</label>
                {{form.area}}
            </div>
            <div class="ten wide field">
                    <label>Address</label>
                    {{form.location}}
                </div>
        </div>
               <div class="ui inverted right aligned segment" style="padding: 0px;">
                    <button class = "ui button green" type="submit" >{{actiontype}}</button>
                </div>
                <div class="ui inverted placeholder segment">
                    <div class="ui two column stackable center aligned grid">
                      <div class="ui vertical divider"></div>
                      <div class="top aligned row">
                        <div class="column">
                      
                            <label>Search Location</label>
                            <div class="ui fluid category search">
                              <div class="ui icon input">
                                {{geosearch.search}}
                                <i class="search icon"></i>
                              </div>
                              <div class="results"></div>
                            </div>
                            <br>
                            <button id = "btn_search" class="ui blue button" type="button">Search</button>

                            <div  id ="id_location_cards"></div>


                        </div>
                        <div class="column">

                            <label>Geotag Location</label>
                          <div id = "id_geomap">
                              {{geoform.point}}
                          </div>

                        </div>
                      </div>
                    </div>
                  </div>
        </form>
</div>
<script>
    $("#btn_search").click(function () {
      var url = 'ajax_load_locations';  // get the url of the `load_locations` view
      var search_query = $("#id_search").val();  // get the search query from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request
        data: {
          'search_query': search_query, // add the search query to the GET parameters
           'width' : {{width}}
        },
        success: function (data) {   // `data` is the return of the `load_locations` view function
          $("#id_location_cards").html(data);  // replace the contents of the #id_location_cards input with the data that came from the server
        },
            error:
         function(xhr){
             alert("Error: " + xhr.statusText);
             //alert(xhr.responseText) --> to get the full details of error
             return false;
             }
      });

    });
  </script>



{% endblock %}