K9_insys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include ('profiles.urls', namespace='profiles')),
    path('deployment/', include('deployment.urls', namespace='deployment')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('planningandacquiring/', include ('planningandacquiring.urls', namespace='planningandacquiring')),
    path('training/', include ('training.urls', namespace='training')),
    path('unitmanagement/', include ('unitmanagement.urls', namespace='unitmanagement')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deployment/urls.py
from django.urls import path
from django.conf.urls import include, url
from .import views

app_name='deployment'
urlpatterns = [
    path('', views.index, name='index'),
    path('add-area/', views.add_area, name='add_area'),
    path('add-location/', views.add_location, name='add_location'),
    path('assign-team-location/', views.assign_team_location, name='assign_team_location'),
    path('assigned-location-list/', views.assigned_location_list, name='assigned_location_list'),
    path('team-location-details/<int:id>', views.team_location_details, name='team_location_details'),
    path('edit-team/<int:id>', views.edit_team, name='edit_team'),
    path('remove-dog-deployed/<int:id>', views.remove_dog_deployed, name='remove_dog_deployed'),
    path('request_form/', views.dog_request, name='request_form'),
    path('request_dog_list/', views.request_dog_list, name='request_dog_list'),
    path('request_dog_details/<int:id>', views.request_dog_details, name='request_dog_details'),
    path('remove-dog-request/<int:id>', views.remove_dog_request, name='remove_dog_request'),
    path('view-schedule/<int:id>', views.view_schedule, name='view_schedule'),
    path('add-incident/', views.add_incident, name='add_incident'),
    path('view-incidents/', views.incident_list, name='view_incidents'),


    path('incident-detail/<int:id>', views.incident_detail, name='incident_detail'),

    path('choose-date/', views.choose_date, name='choose_date'),
    path('choose-date/deployment-report/', views.deployment_report, name='deployment_report'),

    path('deployment-area-details/', views.deployment_area_details, name='deployment_area_details'),
    path('fou-details/', views.fou_details, name='fou_details'),
    path('daily-refresher-form', views.daily_refresher_form, name='daily_refresher_form'),


    path('add-location/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('add-location/ajax_load_map', views.load_map, name='ajax_load_map'),
    path('request_form/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('request_form/ajax_load_map', views.load_map, name='ajax_load_map'),

    path('choose-location/', views.choose_location, name='choose_location'),
    path('choose-location/ajax_load_units', views.load_units, name='ajax_load_units'),
    path('choose-location/ajax_load_units_selected', views.load_units_selected, name='ajax_load_units_selected'),

    path('schedule-units', views.schedule_units, name = 'schedule_units'),

    path('pre_req_unconfirmed', views.pre_req_unconfirmed, name='pre_req_unconfirmed'),
    path('pre_req_unconfirmed/ajax_load_pre_req', views.load_pre_req, name='load_pre_req'),

    # path('dogs-deployed', views.deployed_dogs, name='deployed_dogs'),
    # path('dogs-requested', views.requested_dogs, name='requested_dogs'),
    # path('deploy-number-dogs', views.deploy_number_dogs, name='deploy_number_dogs'),
    # path('location-form', views.location_form, name='location_form'),
    # path('assign_team/', views.assign_team, name='assign_team'),
    # path('load-teams/', views.load_teams, name='ajax_load_teams'),  # <-- this one here
    # path('area_list/', views.area_list_view, name='area_list'),
    # path('add_location/', views.area_form, name='add_location'),
    # path('add_team/', views.team_form, name='add_team'),
    # path('area_detail/<int:id>', views.area_list_detail, name='area_detail'),
    #path('/<int:id>/', views., name=''),
];

profiles/urls.py
from django.urls import path
from django.conf.urls import include, url
from .import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from rest_framework import routers

router = routers.DefaultRouter()
router.register('user', views.UserView)


app_name='profiles'
urlpatterns = [
    path('team-leader-dashboard/', views.team_leader_dashboard, name='team_leader_dashboard'),
    path('handler-dashboard/', views.handler_dashboard, name='handler_dashboard'),
    path('vet-dashboard/', views.vet_dashboard, name='vet_dashboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('commander-dashboard/', views.commander_dashboard, name='commander_dashboard'),
    path('operations-dashboard/', views.operations_dashboard, name='operations_dashboard'),
    path('trainer-dashboard/', views.trainer_dashboard, name='trainer_dashboard'),

    path('profile/', views.profile, name='profile'),
    path('notifications/', views.notif_list, name='notif_list'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('home/', views.home, name='home'),
    path('add_User_form/', views.add_User, name='add_User_form'),
    path('add_User_form/add_personal_form/', views.add_personal_info, name='add_personal_form'),
    path('add_User_form/add_personal_form/add_education/', views.add_education, name='add_education'),
    path('add_User_form/add_personal_form/add_education/add_user_account/', views.add_user_account, name='add_user_account'),
    path('user_list/', views.user_listview, name='user_list'),
    path('user_detail/<int:id>', views.user_detailview, name='user_detail'),
    path('user_add_confirmed/', views.user_add_confirmed, name='user_add_confirmed'),
    
    path('dashboard/update_event/', views.update_event, name='update_event'),

    path('api', views.NotificationListView.as_view()),
    path('api/<int:id>', views.NotificationDetailView.as_view()),

    path('handler-dashboard/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('handler-dashboard/ajax_load_map', views.load_map, name='ajax_load_map'),
    
    path('operations-dashboard/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('operations-dashboard/ajax_load_map', views.load_map, name='ajax_load_map'),
    path('team-leader-dashboard/ajax_load_locations', views.load_locations, name='ajax_load_locations'),
    path('team-leader-dashboard/ajax_load_map', views.load_map, name='ajax_load_map'),

    path('operations-dashboard/ajax_load_event', views.load_event, name = "ajax_load_event"),
    path('team-leader-dashboard/ajax_load_event', views.load_event, name = "ajax_load_event"),
    path('commander-dashboard/ajax_load_event', views.load_event, name = "ajax_load_event"),
    path('dashboard/ajax_load_event', views.load_event, name = "ajax_load_event"),
    path('handler-dashboard/ajax_load_event_handler', views.load_event_handler, name = "ajax_load_event_handler"),

    path('schedule/api', views.ScheduleView.as_view()),
    path('handler-dashboard/team-location-details/<int:id>', views.team_location_details, name='team_location_details'),
    path('handler-dashboard/request_dog_details/<int:id>', views.request_dog_details, name='request_dog_details'),

    # path('user/api', views.UserListView.as_view()),
    # path('user/api/<int:id>', views.UserDetailView.as_view()),

    path('user/api', include(router.urls)),

];

unitmanagement/urls.py
from django.urls import path
from django.conf.urls import include, url
from .import views
from django.views.generic import TemplateView

app_name='unitmanagement'
urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('health-form', views.health_form, name='health_form'),
    path('health-record', views.health_record, name='health_record'),
    path('health-history/<int:id>', views.health_history, name='health_history'),
    path('health-history-handler', views.health_history_handler, name='health_history_handler'),
    path('health-details/<int:id>', views.health_details, name='health_details'),
    path('physical-exam-details/<int:id>', views.physical_exam_details, name='physical_exam_details'),
    path('approve-medicine/<int:id>', views.medicine_approve, name='medicine_approve'),
    # path('request-form', views.requests_form, name='request_form'),
    #path('request-list', views.request_list, name='request_list'),
    path('k9-incident', views.k9_incident, name='k9_incident'),
    path('handler-incident-form', views.handler_incident_form, name='handler_incident_form'),
    path('reproductive-list', views.reproductive_list, name='reproductive_list'),
    path('reproductive-edit/<int:id>', views.reproductive_edit, name='reproductive_edit'),
    path('k9-unpartnered-list', views.k9_unpartnered_list, name='k9_unpartnered_list'),
    path('choose-handler-list/<int:id>', views.choose_handler_list, name='choose_handler_list'),
    path('choose-handler/<int:id>', views.choose_handler, name='choose_handler'),
    path('k9-sick-form', views.k9_sick_form, name='k9_sick_form'),
    path('k9-sick-list', views.k9_sick_list, name='k9_sick_list'),
    path('k9-sick-details/<int:id>', views.k9_sick_details, name='k9_sick_details'),
    path('on-leave-request', views.on_leave_request, name='on_leave_request'),
    path('on-leave-list', views.on_leave_list, name='on_leave_list'),
    path('on-leave-decision/<int:id>', views.on_leave_decision, name='on_leave_decision'),
    # path('on-leave-details/<int:id>', views.on_leave_details, name='on_leave_details'),

    path('transfer-request-form', views.transfer_request_form, name='transfer_request_form'),
    path('transfer-request-list', views.transfer_request_list, name='transfer_request_list'),
    path('due-retired-list', views.due_retired_list, name='due_retired_list'),
    path('due-retired-call/<int:id>', views.due_retired_call, name='due_retired_call'),

    path('called-back-list', views.confirm_base_arrival, name='confirm_base_arrival'),
    path('confirm_arrive/<int:id>', views.confirm_arrive, name='confirm_arrive'),
    path('confirm_going_back/<int:id>', views.confirm_going_back, name='confirm_going_back'),

    path('unfit-list', views.unfit_list, name='unfit_list'),
    path('health-list', views.health_list_handler, name='health_list_handler'),
    path('k9-incident-list', views.k9_incident_list, name='k9_incident_list'),
    path('k9-retrieved/<int:id>', views.k9_retreived, name='k9_retreived'),
    path('follow-up/<int:id>', views.follow_up, name='follow_up'),

    path('yearly-vaccine-list', views.yearly_vaccine_list, name='yearly_vaccine_list'),
    path('vaccination-list', views.vaccination_list, name='vaccination_list'),
    path('vaccine_submit', views.vaccine_submit, name='vaccine_submit'),
    #path('choose-date/<int:id>', views.choose_date, name='choose_date'),

    path('redirect-notif/<int:id>', views.redirect_notif, name='redirect_notif'),

    path('choose-handler-list/ajax_load_handler', views.load_handler, name='ajax_load_handler'),
    path('health-history/ajax_load_stamp', views.load_stamp, name='ajax_load_stamp'),
    path('ajax_load_k9', views.load_k9, name='ajax_load_k9'),

    path('k9-sick-details/ajax_load_health', views.load_health, name='ajax_load_health'),
    path('k9-incident-list/ajax_load_incident', views.load_incident, name='ajax_load_incident'),
    path('k9-sick-details/ajax_load_image', views.load_image, name='ajax_load_image'),
    path('yearly-vaccine-list/ajax_load_yearly_vac', views.load_yearly_vac, name='ajax_load_yearly_vac'),
    path('vaccination-list/ajax_load_yearly_vac', views.load_yearly_vac, name='ajax_load_yearly_vac'),
    path('unfit-list/ajax_load_physical', views.load_physical, name='ajax_load_physical'),
    path('reassign-assets/ajax_load_handler', views.load_handler, name='load_handler'),
    path('trained-list/ajax_load_k9_data', views.load_k9_data, name='ajax_load_k9_data'),
    path('transfer-request-list/ajax_load_transfer', views.load_transfer, name='load_transfer'),

    path('reassign-assets/<int:id>', views.reassign_assets, name='reassign_assets'),
    # path('confirm-death/<int:id>', views.confirm_death, name='confirm_death'),
    path('trained-list', views.trained_list, name='trained_list'),
    path('classified-list', views.classified_list, name='classified_list'),
    #path('change-equipment/<int:id>', views.change_equipment, name='change_equipment'),
    path('transfer-request-list/ajax_load_handler', views.load_handler, name='ajax_load_handler'),

    path('replenishment_form', views.replenishment_form, name='replenishment_form'),
    path('replenishment_form/ajax_load_item', views.load_item, name='load_item'),
    path('replenishment_form/ajax_load_item_food', views.load_item_food, name='load_item_food'),
    path('replenishment_form/ajax_load_item_med', views.load_item_med, name='load_item_med'),
    path('replenishment_form/ajax_load_item_misc', views.load_item_misc, name='load_item_misc'),

    path('replenishment_confirm', views.replenishment_confirm, name='replenishment_confirm'),
    path('replenishment_approval/<int:id>', views.replenishment_approval, name='replenishment_approval'),
    path('load_item/', views.load_item, name='load_item'),


    path('confirm_item_request/<int:id>', views.confirm_item_request, name='confirm_item_request'),

    path('team-leader/api', views.TeamLeaderView.as_view()),
    path('handler/api', views.HandlerView.as_view()),
    path('vet/api', views.VetView.as_view()),
    path('commander/api', views.CommanderView.as_view()),
    path('trainer/api', views.TrainerView.as_view()),
    path('admin/api', views.AdminView.as_view()),


    path('k9-checkup-pending', views.k9_checkup_pending, name='k9_checkup_pending'),
    path('ajax_load_appointments', views.load_appointments, name='ajax_load_appointments'),
    path('ajax_load_checkups', views.load_checkups, name='ajax_load_checkups'),

    path('k9-checkup-list-today', views.k9_checkup_list_today, name = 'k9_checkup_list_today'),
    path('physical-exam-form/', views.physical_exam_form, name='physical_exam_form'),
    path('physical-exam-form/<int:id>', views.physical_exam_form, name='physical_exam_form'),

    path('k9-mia-list', views.k9_mia_list, name ='k9_mia_list'),
    path('k9_mia_change/<int:id>', views.k9_mia_change, name ='k9_mia_change'),
    # add in unitmanagement urls.py
    path('replenishment_form/ajax_load_item', views.load_item, name='load_item'),
    path('k9_accident/<int:id>', views.k9_accident, name ='k9_accident'),
    path('k9_accident', views.k9_accident, name ='k9_accident'),
    #path('/<int:id>/', views., name=''),

    path('emergency_leave_list', views.emeregency_leave_list, name ='emergency_leave_list'),
    path('handler_status_mia/<int:id>', views.handler_status_mia, name ='handler_status_mia'),
    path('k9_accident_death_handler', views.k9_accident_death_handler, name ='k9_accident_death_handler'),

    path('replenishment_confirm/ajax_load_replenishment', views.load_replenishment, name='load_replenishment'),
    
    path('mia_fou/<int:id>', views.mia_fou, name ='mia_fou'),

    # path('returning_handlers_list', views.returning_handlers_list, name ='returning_handlers_list'),
];

profiles/templates/profiles/load_event.html
{% load static %}
{% block content %}
<div class="ui modal" id ="event_modal">
<div class="header">Requester: {{dog_request.requester}}</div>
  <div class="content">
      <table class="ui basic table">
    <thead>
    <tr>
        <th class="two wide">Event Name</th>
        <td>{{dog_request.event_name}}</td>

        <th class="two wide">Email</th>
        <td>{{dog_request.email_address}}</td>

        <th class="two wide">Start Date</th>
        <td>{{dog_request.start_date}}</td>

        <th class="two wide">End Date</th>
        <td>{{dog_request.end_date}}</td>
    </tr>
    </thead>
</table>
        <h4>Location</h4>
      <textarea rows="4" cols="50" disabled="disabled">
{{dog_request.location}}}
</textarea>

      <h4>Remarks</h4>
      <textarea rows="4" cols="50" disabled="disabled">
{{dog_request.remarks}}
</textarea>




  </div>
</div>



 {% endblock %}

profiles/templates/profiles/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>K9 Coast Guard</title>

    <link rel="stylesheet" href="{% static 'Semantic-UI/semantic.min.css' %}">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'Semantic-UI/semantic.min.js' %}"></script>
    <!-- <script src="{% static 'custome/custom_jquery.js' %}"></script> -->
    <!-- <link rel="stylesheet" href="{% static 'custom/custom_style.css' %}"> -->
</head>
<body style="background-color: orangered;">
    <!--START OF TOP MENU-->
        <div class="ui inverted top attached menu" style="padding:5px;">
            <div class="right menu">
                <a class="ui item" href="{% url 'profiles:register'%}" style="font-weight: bold;color: orangered;">SIGN-UP</a>
                <a class="ui item" href="{% url 'profiles:login'%}" style="font-weight: bold;color: orangered;">LOGIN</a>
            </div>
        </div>
    <!--END OF TOP MENU-->

    <div class="ui bottom attached segment" id = 'bg' style="height:89%;">
        <div class="ui three column centered grid">
            <div class="column center aligned" style="background:transparent;border-radius:20px;margin-top: 3%;" class ='screen_centered'>
                <img src="{% static 'images/k9_logo.png' %}">
                <div class="ui inverted segment">
                    <form class="ui inverted equal width form" method="POST">
                        {% csrf_token %}
                        <div class="field">
                            <label>SERIAL NUMBER</label>
                            <input placeholder="" name='serial_number' type="text">
                        </div>
                        <div class="field">
                            <label>PASSWORD</label>
                            <input placeholder="" name='password' type="password">
                        </div>
                        {% if messages %}
                            {% for message in messages %}
                                <div style="color: red;margin-bottom: 2px;"> {{ message }}</div>
                            {% endfor %}
                        {% endif %}
                        <div class="center aligned">
                        <button class = "ui button green" type="submit" onclick="return confirm('Are you sure?')">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
<style>
    /* #bg{
        background-size: cover;
        background-repeat: no-repeat;
        position: relative;
        background-image: url('{% static "images/qwe2.jpg"%}');
        background-size: 100% 100%;
    } */

    .screen_centered {
        position: fixed;
        margin-top: 10%;
        left: 50%;
        /* bring your own prefixes */
        transform: translate(-50%, -50%);
    }

</style>

    {% block script%}
    {% endblock%}

</html>

profiles/templates/profiles/map_data.html
{{geoform.point}}

profiles/templates/profiles/sidebar_um.html
{% extends "profiles/global-base-ui/sidebar_menu.html" %}

{% block sidebar_module %}
    <div class="ui fluid container">
        <div class="ui basic segment">
            <div class="ui grid">
                <div class="three wide column">
                        <div class="ui pointing vertical menu">
                            <a class="item"> <b>Unit Management Menu</b></a>
                            {% if request.session.session_user_position == "Administrator" %}
                            <a href="{% url 'profiles:add_User_form'%}" class="item">
                                <i class="user plus icon"></i>Add User Form
                            </a>
                            <a href="{% url 'profiles:user_list'%}" class="item">
                                <i class="address book icon"></i>User List
                            </a>
                            <a href="{% url 'unitmanagement:classified_list'%}" class="item">
                                <i class="clipboard list icon"></i>Classified List
                            </a>
                            <a href="{% url 'unitmanagement:k9_unpartnered_list'%}" class="item">
                                <i class="retweet icon"></i>Reallocate Assets
                            </a>
                            <a href="{% url 'unitmanagement:on_leave_list'%}" class="item">
                                <i class="clipboard list icon"></i>On-Leave Request list
                            </a>
                            <a href="{% url 'unitmanagement:transfer_request_list'%}" class="item">
                                <i class="clipboard list icon"></i>Transfer Request list
                            </a>
                            <a href="{% url 'unitmanagement:k9_incident_list'%}" class="item">
                                <i class="clipboard list icon"></i>K9 Incident List
                            </a>
                            <a href="{% url 'unitmanagement:due_retired_list'%}" class="item">
                                    <i class="clipboard list icon"></i>Due for
                                    Retirement List
                                </a>
                            <a href="{% url 'unitmanagement:k9_mia_list'%}" class="item">
                                    <i class="clipboard list icon"></i>MIA List
                                </a>
                            <a href="{% url 'unitmanagement:emergency_leave_list'%}" class="item">
                                <i class="clipboard list icon"></i>Emergency Leave List
                            </a>


                            {% elif request.session.session_user_position == "Veterinarian" %}
                            <!-- <a href="{% url 'profiles:add_User_form'%}" class="item">
                                <i class="user plus icon"></i>Add User Form
                            </a>
                            <a href="{% url 'profiles:user_list'%}" class="item">
                                <i class="address book icon"></i>User List
                            </a> -->
                            <a href="{% url 'unitmanagement:health_form'%}" class="item">Health Form
                                <i class="first aid icon"></i>
                            </a>
                            <a href="{% url 'unitmanagement:physical_exam_form'%}" class="item">
                                <i class="heartbeat icon"></i>Physical Exam Form
                            </a>
                            <a href="{% url 'unitmanagement:trained_list'%}" class="item">
                                <i class="clipboard list icon"></i>Trained K9 List
                            </a>

                            <a href="{% url 'unitmanagement:unfit_list'%}" class="item">
                                <i class="clipboard list icon"></i>Unfit K9 List
                            </a>
                            <a href="{% url 'unitmanagement:yearly_vaccine_list'%}" class="item">
                                <i class="clipboard list icon"></i>Yearly Vaccine K9 List
                            </a>
                            <a href="{% url 'unitmanagement:k9_sick_list'%}" class="item">
                                <i class="ambulance icon"></i>Sick K9's List
                            </a>
                            <a href="{% url 'unitmanagement:k9_incident_list'%}" class="item">
                                <i class="clipboard list icon"></i>K9 Incident List
                            </a>
                            <a href="{% url 'unitmanagement:health_record'%}" class="item">
                                <i class="h square icon"></i>Health Records
                            </a>
                            <a href="{% url 'unitmanagement:reproductive_list'%}" class="item">
                                <i class="venus icon"></i>Reproductive Cycle
                            </a>
                             <a href="{% url 'unitmanagement:k9_checkup_pending'%}" class="item">
                                <i class="calendar icon"></i>Schedule K9 Checkups for Initial Deployment
                            </a>
                            <a href="{% url 'unitmanagement:k9_checkup_list_today'%}" class="item">
                                <i class="clipboard list icon"></i>K9s for Checkup
                            </a>


                            {% elif request.session.session_user_position == "Handler" %}

                            {% if request.session.partnered == True %}
                                <a href="{% url 'deployment:daily_refresher_form'%}" class="item">
                                    <i class="sync alternate icon"></i>Daily Refresher Form
                                </a>
                                <a href="{% url 'unitmanagement:k9_sick_form'%}" class="item">
                                    <i class="medkit icon"></i>K9 Health Form
                                </a>
                                <a href="{% url 'unitmanagement:k9_incident'%}" class="item">
                                    <i class="exclamation icon"></i>
                                    <i class="paw icon"></i>K9-Incident Form
                                </a>
                                <a href="{% url 'unitmanagement:health_history_handler'%}" class="item">
                                    <i class="h square icon"></i>Health Records
                                </a>

                                <a href="{% url 'unitmanagement:health_list_handler'%}" class="item">
                                    <i class="clipboard list icon"></i>Health Concern List
                                </a>
                            {% endif %}
                            <a href="{% url 'unitmanagement:on_leave_request'%}" class="item">
                                <i class="share square icon"></i>Apply for Leave
                            </a>
                            <a href="{% url 'unitmanagement:transfer_request_form'%}" class="item">
                                <i class="globe icon"></i>Request for Transfer
                            </a>


                            {% elif request.session.session_user_position == "Team Leader" %}
                            <a href="{% url 'unitmanagement:replenishment_form'%}" class="item">
                                <i class="exclamation icon"></i>Replenish Assets
                            </a>
                            <a href="{% url 'unitmanagement:handler_incident_form'%}" class="item">
                                <i class="id badge icon"></i>
                                <i class="exclamation icon"></i>Handler Incident Form
                            </a>
                            <a href="{% url 'unitmanagement:on_leave_request'%}" class="item">
                                <i class="share square icon"></i>Apply for Leave
                            </a>
                            <a href="{% url 'unitmanagement:transfer_request_form'%}" class="item">
                                <i class="globe icon"></i>Request for Transfer
                            </a>

                            {% elif request.session.session_user_position == "Operations" %}

                            {% else %}
                            <a href="{% url 'deployment:deployment_area_details'%}" class="item">
                                <i class="building icon"></i>Assigned Area Details
                            </a>
                            <a href="{% url 'deployment:fou_details'%}" class="item">
                                    <i class="id card icon"></i>FOU's Details
                            </a>
                            <a href="{% url 'unitmanagement:k9_incident_list'%}" class="item">
                                <i class="clipboard list icon"></i>K9 Incident List
                            </a>
                            <a href="{% url 'deployment:add_incident'%}" class="item">
                                <i class="pen square icon"></i>
                                <i class="exclamation icon"></i>Incident Form
                            </a>
                            <a href="{% url 'unitmanagement:handler_incident_form'%}" class="item">
                                <i class="id badge icon"></i>
                                <i class="exclamation icon"></i>Handler Incident
                                Form
                            </a>

                            {% endif %}

                        </div>
                </div>
                <!>
                <div class="thirteen wide column">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
</div>

      <style>
          .submenu{
                color: #666666;
                display: block;
                font-family: 'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif;
                display: list-item;
                table-layout: fixed;
                background-color: transparent;
                list-style-type: none;
                list-style-position: outside;
                line-height: 1.14285714em;

            }
            .submenu:hover{
                color: black;
            }
            .subdiv{
                display: flex;
                padding: 8px;
                flex-wrap: wrap;
                justify-content: space-between;
            }

      </style>
{% endblock%}

profiles/templates/profiles/user_add_confirmed.html
{% extends "profiles/sidebar_um.html" %} {% block content %}

<div class="ui icon message">
  <i class="green check icon"></i>
  <div class="content">
    <div class="header">
      You have succesfully added a User to the database!
    </div>
    <p>Head over to navigation to continue with operations.</p>
  </div>
</div>

{% endblock %}