K9_insys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include ('profiles.urls', namespace='profiles')),
    path('deployment/', include('deployment.urls', namespace='deployment')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('planningandacquiring/', include ('planningandacquiring.urls', namespace='planningandacquiring')),
    path('training/', include ('training.urls', namespace='training')),
    path('unitmanagement/', include ('unitmanagement.urls', namespace='unitmanagement')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from django.conf.urls import include, url
from .import views

app_name='inventory'
urlpatterns = [
    path('', views.index, name='index'),
    #Medicine
    path('add-medicine', views.medicine_add, name='medicine_add'),
    path('edit-medicine/<int:id>/', views.medicine_edit, name='medicine_edit'),
    #Food
    path('add-food', views.food_add, name='food_add'),
    path('edit-food/<int:id>/', views.food_edit, name='food_edit'),
    #Miscellaneous
    path('add-miscellaneous', views.miscellaneous_add, name='miscellaneous_add'),
    path('edit-miscellaneous/<int:id>/', views.miscellaneous_edit, name='miscellaneous_edit'),
    #Inventory
    path('list-medicine-inventory', views.medicine_inventory_list, name='medicine_inventory_list'),
    path('list-food-inventory', views.food_inventory_list, name='food_inventory_list'),
    path('list-miscellaneous-inventory', views.miscellaneous_inventory_list, name='miscellaneous_inventory_list'),
    #inventory Details List
    path('medicine-inventory-details/<int:id>/', views.medicine_inventory_details, name='medicine_inventory_details'),
    path('food-inventory-details/<int:id>/', views.food_inventory_details, name='food_inventory_details'),
    path('miscellaneous-inventory-details/<int:id>/', views.miscellaneous_inventory_details, name='miscellaneous_inventory_details'),
    #inventory Count Form
    path('medicine-count-form/<int:id>/', views.medicine_count_form, name='medicine_count_form'),
    path('food-count-form/<int:id>/', views.food_count_form, name='food_count_form'),
    path('miscellaneous-count-form/<int:id>/', views.miscellaneous_count_form, name='miscellaneous_count_form'),
    #inventory Receive Form
    path('medicine-receive-form/<int:id>/', views.medicine_receive_form, name='medicine_receive_form'),
    path('food-receive-form/<int:id>/', views.food_receive_form, name='food_receive_form'),
    path('miscellaneous-receive-form/<int:id>/', views.miscellaneous_receive_form, name='miscellaneous_receive_form'),
    #inventory Subtract Form
    path('medicine-subtract-form/<int:id>/', views.medicine_subtract_form, name='medicine_subtract_form'),
    path('food-subtract-form/<int:id>/', views.food_subtract_form, name='food_subtract_form'),
    path('miscellaneous-subtract-form/<int:id>/', views.miscellaneous_subtract_form, name='miscellaneous_subtract_form'),
    #damaged form
    path('damaged-form', views.damaged_form, name='damaged_form'),
    path('damaged-report-list', views.damaged_report_list, name='damaged_report_list'),
];

inventory/forms.py
from django import forms
from django.forms import ModelForm, ValidationError, Form, widgets
from django.contrib.admin.widgets import AdminDateWidget
from datetime import date, datetime

from inventory.models import Medicine, Food, Miscellaneous, Medicine_Inventory
from inventory.models import DamagedEquipemnt

class DateInput(forms.DateInput):
    input_type = 'date'

#Medicine
class MedicineForm(forms.ModelForm):

    UOM = (
        ('mg', 'mg'),
        ('mL', 'mL'),
        ('suspension', 'suspension'),
    )

    uom = forms.CharField(max_length=10, label = 'uom', widget = forms.Select(choices=UOM))
    description = forms.CharField(widget = forms.Textarea(attrs={'rows':'3'}))
    dose = forms.DecimalField(widget = forms.NumberInput())

    class Meta:
        model = Medicine
        fields = ('medicine', 'dose', 'uom', 'description', 'price', 'med_type','immunization')

    def __init__(self, *args, **kwargs):
        super(MedicineForm, self).__init__(*args, **kwargs)
        self.fields['description'].required = False
        self.fields['uom'].required = False 
        self.fields['dose'].required = False 
        self.fields['immunization'].required = False 

class MedicineCountForm(forms.ModelForm):
    class Meta:
        model = Medicine_Inventory
        fields = ('medicine', 'quantity')
    
    def __init__(self, *args, **kwargs):
        super(MedicineCountForm, self).__init__(*args, **kwargs)
        self.fields['medicine'].required = False
        
        
#Food
class FoodForm(forms.ModelForm):
    description = forms.CharField(widget = forms.Textarea(attrs={'rows':'3'}))
    
    class Meta:
        model = Food
        fields = ('food', 'foodtype', 'description', 'price','unit')

    def __init__(self, *args, **kwargs):
        super(FoodForm, self).__init__(*args, **kwargs)
        self.fields['description'].required = False

class FoodCountForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ('food', 'quantity')

    def __init__(self, *args, **kwargs):
        super(FoodCountForm, self).__init__(*args, **kwargs)
        self.fields['food'].required = False

#Miscellaneous
class MiscellaneousForm(forms.ModelForm):

    UOM = (
        ('pc', 'pc'),
        ('pack', 'pack'),
        ('box', 'box'),
        ('roll', 'roll'),
        ('can', 'can'),
        ('bottle', 'bottle'),
        ('tube', 'tube'),
    )

    TYPE = (    
        ('Vet Supply', 'Vet Supply'),
        ('Kennel Supply', 'Kennel Supply'),
        ('Others', 'Others'),
    )

    description = forms.CharField(widget = forms.Textarea(attrs={'rows':'3'}))
    uom = forms.CharField(max_length=100, label = 'uom', widget = forms.Select(choices=UOM))
    misc_type = forms.CharField(max_length=100, label = 'misc_type', widget = forms.Select(choices=TYPE))

    class Meta:
        model = Miscellaneous
        fields = ( 'miscellaneous', 'description', 'uom', 'price', 'misc_type')

    def __init__(self, *args, **kwargs):
        super(MiscellaneousForm, self).__init__(*args, **kwargs)
        self.fields['description'].required = False

class MiscellaneousCountForm(forms.ModelForm):
    class Meta:
        model = Miscellaneous
        fields = ('miscellaneous', 'quantity')

    def __init__(self, *args, **kwargs):
        super(MiscellaneousCountForm, self).__init__(*args, **kwargs)
        self.fields['miscellaneous'].required = False

class DamagedEquipmentForm(forms.ModelForm):
    CONCERN = (
        ('Broken', 'Broken'),
        ('Lost', 'Lost'),
        ('Stolen', 'Stolen'),
    )

    concern = forms.CharField(max_length=10, label = 'concern', widget = forms.Select(choices=CONCERN))
    inventory = forms.ModelChoiceField(queryset = Miscellaneous.objects.filter(misc_type="Equipment").order_by('miscellaneous'))

    class Meta:
        model = DamagedEquipemnt
        fields = ('inventory', 'quantity', 'concern')

inventory/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory, inlineformset_factory
from django.db.models import aggregates
from django.contrib import messages
import datetime
from django.db.models import Sum
from django.contrib.sessions.models import Session
from profiles.models import User, Account
from inventory.models import Medicine, Food, Miscellaneous, Medicine_Inventory, Safety_Stock
from inventory.models import Medicine_Inventory_Count, Food_Inventory_Count, Miscellaneous_Inventory_Count
from inventory.models import Medicine_Received_Trail, Food_Received_Trail, Miscellaneous_Received_Trail, DamagedEquipemnt
from inventory.models import Medicine_Subtracted_Trail, Food_Subtracted_Trail, Miscellaneous_Subtracted_Trail
from unitmanagement.models import Notification
from inventory.forms import MedicineForm, FoodForm, MiscellaneousForm, DamagedEquipmentForm
from inventory.forms import MedicineCountForm, FoodCountForm, MiscellaneousCountForm
# Create your views here.


def notif(request):
    serial = request.session['session_serial']
    account = Account.objects.get(serial_number=serial)
    user_in_session = User.objects.get(id=account.UserID.id)
    
    if user_in_session.position == 'Veterinarian':
        notif = Notification.objects.filter(position='Veterinarian').order_by('-datetime')
    elif user_in_session.position == 'Handler':
        notif = Notification.objects.filter(user=user_in_session).order_by('-datetime')
    else:
        notif = Notification.objects.filter(position='Administrator').order_by('-datetime')
   
    return notif

def user_session(request):
    serial = request.session['session_serial']
    account = Account.objects.get(serial_number=serial)
    user_in_session = User.objects.get(id=account.UserID.id)
    return user_in_session

def index(request):
    return render (request, 'inventory/index.html')

#Medicine
def medicine_add(request):
    form = MedicineForm(request.POST)
    style = "ui teal message"
    if request.method == 'POST':
        print(form.errors)
        if form.is_valid():
            form.save()
    
            style = "ui green message" 
            messages.success(request, 'Medicine has been successfully Added!')
            form = MedicineForm()
        else:
            style = "ui red message"
            messages.warning(request, 'Invalid input data!')

    #NOTIF SHOW
    notif_data = notif(request)
    count = notif_data.filter(viewed=False).count()
    user = user_session(request)
    context = {
        'form': form,
        'title': 'Medicine Form',
        'texthelp': 'Input Medicine data here',
        'actiontype': 'Submit',
        'style' : style,
        'notif_data':notif_data,
        'count':count,
        'user':user,
    }
    return render (request, 'inventory/medicine_add.html',context)

def medicine_edit(request, id):
    item = Medicine.objects.get(id=id)
    form = MedicineForm(request.POST or None, instance = item)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('../../list-medicine')
    
    #NOTIF SHOW
    notif_data = notif(request)
    count = notif_data.filter(viewed=False).count()
    user = user_session(request)
    context = {
        'form': form,
        'title': 'Edit Medicine Form',
        'texthelp': 'Edit Medicine data here',
        'actiontype': 'Submit',
        'notif_data':notif_data,
        'count':count,
        'user':user,
    }
    return render (request, 'inventory/medicine_add.html',context)

#Food
def food_add(request):
    form = FoodForm(request.POST)
    style = "ui teal message"
    if request.method == 'POST':
        print(form.errors)
        if form.is_valid():
            form.save()
            #save in food inventory
            # data_id = Food.objects.last() 
            # Food_Inventory.objects.create(food = data_id, quantity = 0)

            style = "ui green message"
            messages.success(request, 'Dog Food has been successfully Added!')
            form = FoodForm()
        else:
            style = "ui red message"
            messages.warning(request, 'Invalid input data!')

    #NOTIF SHOW
    notif_data = notif(request)
    count = notif_data.filter(viewed=False).count()
    user = user_session(request)
    context = {
        'form': form,
        'title': 'Dog Food Form',
        'texthelp': 'Input Dog food data here',
        'actiontype': 'Submit',
        'style' : style,
        'notif_data':notif_data,
        'count':count,
        'user':user,
    }
    return render (request, 'inventory/food_add.html', context)

def food_edit(request, id):
    item = Food.objects.get(id=id)
    form = FoodForm(request.POST or None, instance = item)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Dog Food has been successfully Edited!')
            return HttpResponseRedirect('../../list-food')

    #NOTIF SHOW
    notif_data = notif(request)
    count = notif_data.filter(viewed=False).count()
    user = user_session(request)
    context = {
        'form': form,
        'title': 'Edit Dog Food Form',
        'texthelp': 'Edit Dog Food data here',
        'actiontype': 'Submit',
        'notif_data':notif_data,
        'count':count,
        'user':user,
    }
    return render (request, 'inventory/food_add.html',context)

#Miscellaneous
def miscellaneous_add(request):
    form = MiscellaneousForm(request.POST)
    style = "ui teal message"
    if request.method == 'POST':
        print(form.errors)
        if form.is_valid():
            form.save()
            
            #save in miscellaneous inventory
            # data_id = Miscellaneous.objects.last() 
            # Miscellaneous_Inventory.objects.create(miscellaneous = data_id, quantity = 0)

            style = "ui green message"
            messages.success(request, 'Miscellaneous Item has been successfully Added!')
            form = MiscellaneousForm()
        else:
            style = "ui red message"
            messages.warning(request, 'Invalid input data!')

    #NOTIF SHOW
    notif_data = notif(request)
    count = notif_data.filter(viewed=False).count()
    user = user_session(request)
    context = {
        'form': form,
        'title': 'Miscellaneous Item Form',
        'texthelp': 'Input Miscellaneous data here',
        'actiontype': 'Submit',
        'style' : style,
        'notif_data':notif_data,
        'count':count,
        'user':user,
    }
    return render (request, 'inventory/miscellaneous_add.html', context)

def miscellaneous_edit(request, id):
    item = Miscellaneous.objects.get(id=id)
    form = MiscellaneousForm(request.POST or None, instance = item)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, 'Miscellaneous Item has been successfully Edited!')
            return HttpResponseRedirect('../../list-miscellaneous')
    
    #NOTIF SHOW
    notif_data = notif(request)
    count = notif_data.filter(viewed=False).count()
    user = user_session(request)
    context = {
        'form': form,
        'title': 'Edit Miscellaneous Form',
        'texthelp': 'Edit Miscellaneous data here',
        'actiontype': 'Submit',
        'notif_data':notif_data,
        'count':count,
        'user':user,
    }
    return render (request, 'inventory/miscellaneous_add.html',context)

#Inventory
def medicine_inventory_list(request):
    data = Medicine_Inventory.objects.all()
    #NOTIF SHOW
    notif_data = notif(request)
    count = notif_data.filter(viewed=False).count()
    user = user_session(request)
    context = {
        'title': 'Medicine Inventory List',
        'data' : data,
        'notif_data':notif_data,
        'count':count,
        'user':user,
    }
    return render (request, 'inventory/medicine_inventory_list.html',context)

def food_inventory_list(request):
    data = Food.objects.all()
    adult_inventory = Food.objects.filter(foodtype='Adult Dog Food').aggregate(sum=Sum('quantity'))['sum']
    puppy_inventory = Food.objects.filter(foodtype='Puppy Dog Food').aggregate(sum=Sum('quantity'))['sum']
    milk_inventory = Food.objects.filter(foodtype='Milk').aggregate(sum=Sum('quantity'))['sum']
    try:
        ss = Safety_Stock.objects.get(id=1)
    except:
        ss = None

    #NOTIF SHOW
    notif_data = notif(request)
    count = notif_data.filter(viewed=False).count()
    user = user_session(request)
    context = {
        'title': 'Dog Food Inventory List',
        'data' : data,
        'ss': ss,
        'adult_inventory': adult_inventory,
        'puppy_inventory': puppy_inventory,
        'milk_inventory': milk_inventory,
        'notif_data':notif_data,
        'count':count,
        'user':user,
    }
    return render (request, 'inventory/food_inventory_list.html',context)

def miscellaneous_inventory_list(request):
    data = Miscellaneous.objects.all()
    #NOTIF SHOW
    notif_data = notif(request)
    count = notif_data.filter(viewed=False).count()
    user = user_session(request)
    context = {
        'title': 'Miscellaneous Inventory List',
        'data' : data,
        'notif_data':notif_data,
        'count':count,
        'user':user,
    }
    return render (request, 'inventory/miscellaneous_inventory_list.html',context)

#Inventory Details
def medicine_inventory_details(request, id):
    i = Medicine_Inventory.objects.get(id=id)
    data = Medicine_Inventory_Count.objects.filter(inventory=id).order_by('-date_counted').order_by('-time')
    data2 = Medicine_Received_Trail.objects.filter(inventory=id).order_by('-date_received').order_by('-time')
    data3 = Medicine_Subtracted_Trail.objects.filter(inventory=id).order_by('-date_subtracted').order_by('-time')

inventory/templates/inventory/choose_date.html
{% extends "profiles/sidebar_inventory.html" %}

{% block content %}
<div class="ui inverted segment" style="padding:20px;">
    <h3 class="ui header">{{ title }}</h3>
    {% if messages %}
        {% for message in messages %}
            <div class="ui green message" > {{ message }}</div>
        {% endfor %}
    {% endif %}
</div>

     <form class="ui form" action="" method="POST">
    {% csrf_token %}
         <div class="two fields">
            {{form.from_date}} to
            {{form.to_date}}
         </div>
         <div class="ui basic center aligned segment">
            <button onclick="return confirm('Are you sure?')" id = "btn" class = "ui button green" type="submit" >Submit</button>
        </div>


    </form>

<script type="text/javascript">

     $(document).ready(function() {
        $('#tabledata1');
        $('#tabledata2');
        $('.menu .item').tab();
    });

</script>
{% endblock %}

inventory/templates/inventory/damaged_form.html
{% extends "profiles/sidebar_inventory.html" %}  

{% block content %}
<div class="ui two column centered grid">
    <div class="column">
        <div class="ui basic segment" style="margin-bottom:0px;">
            <h2 class="ui header">
                {{title}}
                <div class="sub header">Input data of Item Concern Here</div>
            </h2>
        </div>
        <div class="ui inverted segment">
            {% if messages %}
                {% for message in messages %}
                    <div class="{{style}}" > {{ message }}</div>
                {% endfor %}
            {% endif %}
            <form class="ui inverted form" method="POST">
                {% csrf_token %}

                <div class="two fields">
                    <div class="field">
                        <label>Equipment</label>
                        {{form.inventory}}
                    </div>
                        
                    <div class="field">
                        <label>Quantity</label>
                        {{form.quantity}}
                    </div>
                </div>
                <div class="field">
                    <label>Concern</label>
                    {{form.concern}}
                </div>

                <div class="ui inverted right aligned segment" style="padding: 0px;">
                    <button onclick="return confirm('Are you sure?')" class = "ui button green" type="submit" >Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
        
    $(document).ready(function() {
        $('#tabledata').DataTable();
        
        $(function() {
            $('#myForm .formset_class').formset({
                prefix: '{{ formset.prefix }}'
            });            
        })
    } );
    
</script>
 {% endblock %}

inventory/templates/inventory/food_inventory_list.html
{% extends "profiles/sidebar_inventory.html" %}  

{% block content %}
<div class="ui inverted segment" style="padding:20px;">
    <h3 class="ui header">{{ title }}</h3>
    {% if messages %}
        {% for message in messages %}
            <div class="ui green message" > {{ message }}</div>
        {% endfor %}
    {% endif %}
</div>

<table id="tabledata" class="ui five column celled table responsive nowrap" style="width:100%">
    <thead>
        <tr>
            <th>Food</th>
            <th>Type</th>
            <th>Quantity</th>
            <th>Unit</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
        <tbody>
            {% for data in data %}
            {% if data.foodtype == 'Adult Dog Food' %}
                {% if adult_inventory <= ss.adult_food%}
                <tr class = 'negative'>
                    <td>
                        <a href="{% url 'inventory:food_inventory_details' data.id %}">{{ data.food }}</a>
                    </td>
                    <td>{{ data.foodtype }}</td>
                    <td>{{ data.quantity }}</td>
                    <td>{{ data.unit }}</td>
                    <td>{{ data.price }}</td>
                    <td class="two wide center aligned">
                        <a href="{% url 'inventory:food_count_form' data.id %}" style="margin-right:10px;">
                            <i class="teal list ol icon"></i>
                        </a>
                        <a href="{% url 'inventory:food_receive_form' data.id %}" style="margin-right:10px;">
                            <i class="teal dolly flatbed icon"></i>
                        </a>
                    </td>       
                </tr>
                {%else%}
                <tr>
                    <td>
                        <a href="{% url 'inventory:food_inventory_details' data.id %}">{{ data.food }}</a>
                    </td>
                    <td>{{ data.foodtype }}</td>
                    <td>{{ data.quantity }}</td>
                    <td>{{ data.unit }}</td>
                    <td>{{ data.price }}</td>
                    <td class="two wide center aligned">
                        <a href="{% url 'inventory:food_count_form' data.id %}" style="margin-right:10px;">
                            <i class="teal list ol icon"></i>
                        </a>
                        <a href="{% url 'inventory:food_receive_form' data.id %}" style="margin-right:10px;">
                            <i class="teal dolly flatbed icon"></i>
                        </a>
                    </td>       
                </tr>
                {%endif%}
            {%endif%}
            {% if data.foodtype == 'Puppy Dog Food' %}
                {% if puppy_inventory <= ss.puppy_food%}
                <tr class = 'negative'>
                    <td>
                        <a href="{% url 'inventory:food_inventory_details' data.id %}">{{ data.food }}</a>
                    </td>
                    <td>{{ data.foodtype }}</td>
                    <td>{{ data.quantity }}</td>
                    <td>{{ data.unit }}</td>
                    <td>{{ data.price }}</td>
                    <td class="two wide center aligned">
                        <a href="{% url 'inventory:food_count_form' data.id %}" style="margin-right:10px;">
                            <i class="teal list ol icon"></i>
                        </a>
                        <a href="{% url 'inventory:food_receive_form' data.id %}" style="margin-right:10px;">
                            <i class="teal dolly flatbed icon"></i>
                        </a>
                    </td>       
                </tr>
                {%else%}
                <tr>
                    <td>
                        <a href="{% url 'inventory:food_inventory_details' data.id %}">{{ data.food }}</a>
                    </td>
                    <td>{{ data.foodtype }}</td>
                    <td>{{ data.quantity }}</td>
                    <td>{{ data.unit }}</td>
                    <td>{{ data.price }}</td>
                    <td class="two wide center aligned">
                        <a href="{% url 'inventory:food_count_form' data.id %}" style="margin-right:10px;">
                            <i class="teal list ol icon"></i>
                        </a>
                        <a href="{% url 'inventory:food_receive_form' data.id %}" style="margin-right:10px;">
                            <i class="teal dolly flatbed icon"></i>
                        </a>
                    </td>       
                </tr>
                {%endif%}
            {%endif%}
            {% if data.foodtype == 'Milk' %}
            {% if milk_inventory <= ss.milk%}
            <tr class = 'negative'>
                <td>
                    <a href="{% url 'inventory:food_inventory_details' data.id %}">{{ data.food }}</a>
                </td>
                <td>{{ data.foodtype }}</td>
                <td>{{ data.quantity }}</td>
                <td>{{ data.unit }}</td>
                <td>{{ data.price }}</td>
                <td class="two wide center aligned">
                    <a href="{% url 'inventory:food_count_form' data.id %}" style="margin-right:10px;">
                        <i class="teal list ol icon"></i>
                    </a>
                    <a href="{% url 'inventory:food_receive_form' data.id %}" style="margin-right:10px;">
                        <i class="teal dolly flatbed icon"></i>
                    </a>
                </td>       
            </tr>
            {%else%}
            <tr>
                <td>
                    <a href="{% url 'inventory:food_inventory_details' data.id %}">{{ data.food }}</a>
                </td>
                <td>{{ data.foodtype }}</td>
                <td>{{ data.quantity }}</td>
                <td>{{ data.unit }}</td>
                <td>{{ data.price }}</td>
                <td class="two wide center aligned">
                    <a href="{% url 'inventory:food_count_form' data.id %}" style="margin-right:10px;">
                        <i class="teal list ol icon"></i>
                    </a>
                    <a href="{% url 'inventory:food_receive_form' data.id %}" style="margin-right:10px;">
                        <i class="teal dolly flatbed icon"></i>
                    </a>
                </td>       
            </tr>
            {%endif%}
            {%endif%}
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
               
        $(document).ready(function() {
	        $('#tabledata').DataTable();
            // $(function() {
            //     $( ".message" ).slideUp( 4000, function() {
                   
            //     });
            // });
        } );
    </script>
 {% endblock %}

inventory/templates/inventory/index.html
{% extends "profiles/sidebar_inventory.html" %}  

{% block content %}
<div class="ui fluid container">
        <h1>Inventory</h1>
</div>
{% endblock%}

inventory/templates/inventory/medicine_inventory_list.html
{% extends "profiles/sidebar_inventory.html" %}

{% block content %}
<div class="ui inverted segment" style="padding:20px;">
    <h3 class="ui header">{{ title }}</h3>
    {% if messages %}
        {% for message in messages %}
            <div class="ui green message" > {{ message }}</div>
        {% endfor %}
    {% endif %}
</div>

<table id="tabledata" class="ui four column celled table responsive nowrap" style="width:100%">
    <thead>
        <tr>
            <th>Medicine</th>
            <th>Dose/Uom</th>
            <th>Quantity</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
        <tbody>
            {% for data in data %}
            <tr>
                <td>
                    <a href="{% url 'inventory:medicine_inventory_details' data.id %}"> {{ data.medicine }}</a>
                </td>
                <td>{{ data.medicine.dosage }}</td>
                <td>{{ data.quantity }}</td>
                <td>{{ data.medicine.price }}</td>
                <td class="two wide center aligned">
                    <a href="{% url 'inventory:medicine_count_form' data.id %}" style="margin-right:10px;">
                        <i class="teal boxes icon"></i>
                    </a>
                    <a href="{% url 'inventory:medicine_receive_form' data.id %}" style="margin-right:10px;">
                        <i class="teal dolly flatbed icon"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">

        $(document).ready(function() {
	        $('#tabledata').DataTable();
            // $(function() {
            //     $( ".message" ).slideUp( 4000, function() {

            //     });
            // });
        } );
    </script>
 {% endblock %}

inventory/templates/inventory/miscellaneous_inventory_list.html
{% extends "profiles/sidebar_inventory.html" %}  

{% block content %}
<div class="ui inverted segment" style="padding:20px;">
    <h3 class="ui header">{{ title }}</h3>
    {% if messages %}
        {% for message in messages %}
            <div class="ui green message" > {{ message }}</div>
        {% endfor %}
    {% endif %}
</div>

<table id="tabledata" class="ui five column celled table responsive nowrap" style="width:100%">
    <thead>
        <tr>
            <th>Miscellaneous</th>
            <th>Type</th>
            <th>Quantity</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
        <tbody>
            {% for data in data %}
            <tr>
                <td>
                    <a href="{% url 'inventory:miscellaneous_inventory_details' data.id %}">{{ data.miscellaneous }} {{ data.uom }}</a>
                </td>
                <td>{{ data.misc_type }}</td>
                <td>{{ data.quantity }}</td>
                <td>{{data.price}}</td>   
                <td class="two wide center aligned">
                    <a href="{% url 'inventory:miscellaneous_count_form' data.id %}" style="margin-right:10px;">
                        <i class="teal list ol icon"></i>
                    </a>
                    <a href="{% url 'inventory:miscellaneous_receive_form' data.id %}" style="margin-right:10px;">
                        <i class="teal dolly flatbed icon"></i>
                    </a>
                    <a href="{% url 'inventory:miscellaneous_subtract_form' data.id %}" style="margin-right:10px;">
                        <i class="teal truck icon"></i>
                    </a>
                </td>    
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
               
        $(document).ready(function() {
	        $('#tabledata').DataTable();
            // $(function() {
            //     $( ".message" ).slideUp( 4000, function() {
                   
            //     });
            // });
        } );
    </script>
 {% endblock %}